import { useState } from "react";
import { useUser } from "@clerk/clerk-react";
import { useNavigate } from "react-router-dom";
import api from "../services/api"; // Your API helper
import toast from "react-hot-toast";
import { Sparkles, Upload, Loader2, Calendar, MapPin, Clock } from "lucide-react";

const CreateEvent = () => {
  const { user } = useUser();
  const navigate = useNavigate();
  
  // Form State
  const [formData, setFormData] = useState({
    title: "",
    date: "",
    time: "",
    venue: "",
    category: "Technical",
    capacity: "",
    description: "",
  });

  // Upload State
  const [image, setImage] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [loading, setLoading] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);

  // Handle Input Change
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // Handle Image Selection
  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImage(file);
      setPreviewUrl(URL.createObjectURL(file)); // Show preview immediately
    }
  };

  // 🤖 AI Generation Function
  const handleGenerateAI = async () => {
    if (!formData.title || !formData.category) {
      return toast.error("Please enter a Title and Category first!");
    }

    setAiLoading(true);
    try {
      const res = await api.post("/ai/generate", {
        title: formData.title,
        category: formData.category,
        mood: "Exciting"
      });
      
      setFormData((prev) => ({ ...prev, description: res.data.description }));
      toast.success("Description generated by AI! 🤖");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate content.");
    } finally {
      setAiLoading(false);
    }
  };

  // 📝 Form Submission
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      let bannerUrl = "";

      // 1. Upload Image (if selected)
      if (image) {
        const imageFormData = new FormData();
        imageFormData.append("image", image);
        
        const uploadRes = await api.post("/upload", imageFormData, {
          headers: { "Content-Type": "multipart/form-data" },
        });
        bannerUrl = uploadRes.data.url;
      } else {
        // Fallback image if user didn't upload one
        bannerUrl = "https://images.unsplash.com/photo-1540575467063-178a50935339?auto=format&fit=crop&w=1000&q=80";
      }

      // 2. Create Event in Database
      await api.post("/events", {
        ...formData,
        bannerUrl,
        registrationDeadline: new Date(formData.date), 
      });

      toast.success("Event Created Successfully! 🎉");
      navigate("/dashboard"); // Redirect to Dashboard

    } catch (error) {
      console.error(error);
      toast.error(error.response?.data?.message || "Something went wrong.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen pt-20 pb-12 px-4 relative z-10">
      <div className="max-w-3xl mx-auto">
        
        {/* Header */}
        <div className="mb-8 text-center">
          <h1 className="text-4xl font-bold text-white mb-2">Create New Event</h1>
          <p className="text-gray-400">Launch your event to the entire campus in seconds.</p>
        </div>

        <form onSubmit={handleSubmit} className="bg-white/10 backdrop-blur-md border border-white/20 rounded-2xl p-8 shadow-2xl space-y-6">
          
          {/* Top Row: Title & Category */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300">Event Title</label>
              <input 
                type="text" name="title" required 
                placeholder="e.g. HackWar 2025"
                className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-indigo-500 outline-none transition"
                onChange={handleChange}
              />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300">Category</label>
              <select 
                name="category" 
                className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-indigo-500 outline-none transition [&>option]:text-black"
                onChange={handleChange}
              >
                <option value="Technical">Technical</option>
                <option value="Cultural">Cultural</option>
                <option value="Sports">Sports</option>
                <option value="Workshop">Workshop</option>
                <option value="Gaming">Gaming</option>
              </select>
            </div>
          </div>

          {/* AI Description Section */}
          <div className="relative space-y-2">
            <div className="flex justify-between items-center">
              <label className="text-sm font-medium text-gray-300">Description</label>
              <button 
                type="button"
                onClick={handleGenerateAI}
                disabled={aiLoading}
                className="text-xs bg-gradient-to-r from-pink-500 to-violet-600 text-white px-3 py-1 rounded-full flex items-center gap-1 hover:opacity-90 transition disabled:opacity-50"
              >
                {aiLoading ? <Loader2 className="animate-spin w-3 h-3" /> : <Sparkles className="w-3 h-3" />}
                Auto-Write with AI
              </button>
            </div>
            <textarea 
              name="description" 
              rows="4" required
              value={formData.description}
              onChange={handleChange}
              className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white focus:ring-2 focus:ring-indigo-500 outline-none transition"
              placeholder="Describe what your event is about..."
            ></textarea>
          </div>

          {/* Middle Row: Date, Time, Venue */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300 flex items-center gap-2"><Calendar size={14}/> Date</label>
              <input type="date" name="date" required onChange={handleChange} className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300 flex items-center gap-2"><Clock size={14}/> Time</label>
              <input type="time" name="time" required onChange={handleChange} className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300 flex items-center gap-2"><MapPin size={14}/> Venue</label>
              <input type="text" name="venue" required placeholder="Audi / Lab 2" onChange={handleChange} className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
          </div>

          {/* Bottom Row: Capacity & Image */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300">Max Capacity</label>
              <input type="number" name="capacity" required onChange={handleChange} className="w-full bg-black/20 border border-white/10 rounded-lg p-3 text-white outline-none focus:ring-2 focus:ring-indigo-500" />
            </div>
            
            <div className="space-y-2">
              <label className="text-sm font-medium text-gray-300">Event Banner</label>
              <div className="relative border-2 border-dashed border-white/20 rounded-lg p-4 flex flex-col items-center justify-center hover:bg-white/5 transition cursor-pointer h-[120px] overflow-hidden group">
                {previewUrl ? (
                  <img src={previewUrl} alt="Preview" className="absolute inset-0 w-full h-full object-cover opacity-80 group-hover:opacity-60 transition" />
                ) : (
                  <div className="text-center text-gray-400">
                    <Upload className="w-8 h-8 mx-auto mb-2 opacity-50" />
                    <span className="text-xs">Click to upload image</span>
                  </div>
                )}
                <input type="file" onChange={handleImageChange} className="absolute inset-0 opacity-0 cursor-pointer" accept="image/*" />
              </div>
            </div>
          </div>

          {/* Submit Button */}
          <button 
            type="submit" 
            disabled={loading}
            className="w-full bg-gradient-to-r from-indigo-600 to-purple-600 text-white py-4 rounded-xl font-bold text-lg hover:shadow-[0_0_20px_rgba(99,102,241,0.5)] transition-all disabled:opacity-50 flex justify-center items-center gap-2"
          >
            {loading ? <><Loader2 className="animate-spin" /> Publishing...</> : "🚀 Publish Event"}
          </button>

        </form>
      </div>
    </div>
  );
};

export default CreateEvent;